import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import TargetCursor from "../components/TargetCursor";
import AnimatedBackground from "./components/AnimatedBackground";
import Providers from "./providers";
import ClickSpark from "../components/ClickSpark";
import Ribbons from "../components/Ribbons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClickSpark
          sparkColor='#2d3895'
          sparkSize={10}
          sparkRadius={15}
          sparkCount={8}
          duration={400}
        >
        <Ribbons
          baseThickness={30}
          colors={["#5227FF"]}
          speedMultiplier={0.5}
          maxAge={500}
          enableFade={false}
          enableShaderEffect={false}
        />
        <AnimatedBackground />
        <TargetCursor />
          <Providers>
          <Navbar />
          {children}
          <Footer />
          
        </Providers>
        </ClickSpark>
      </body>
    </html>
  );
}
