import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import AnimatedBackground from "./components/AnimatedBackground";
import ClickSpark from "../components/ClickSpark";
import SplashCursor from "../components/SplashCursor";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <ClickSpark
            sparkColor="#2d3895"
            sparkSize={10}
            sparkRadius={15}
            sparkCount={8}
            duration={400}
          >
            <AnimatedBackground />
            {/* <TargetCursor /> */}

            <SplashCursor
              DENSITY_DISSIPATION={10}
              VELOCITY_DISSIPATION={10}
              PRESSURE={0.15}
              CURL={3}
              SPLAT_RADIUS={0.1}
              SPLAT_FORCE={3000}
              COLOR_UPDATE_SPEED={10}
              SHADING
              RAINBOW_MODE={false}
              COLOR="#2d3895"
            />
            <Navbar />
            {children}
            <Footer />
          </ClickSpark>
        </body>
      </html>
    </ClerkProvider>
  );
}
